#!/usr/bin/python
"""Wifi Tracker.

Usage:
    {basename} sniff <interface> [options]
    {basename} -h | --help
    {basename} --version

Options:
    -h --help           Show help.
    --debug             Print debugging messages.

Commands:
    sniff           Sniff probe requests sent by devices in your area.
"""

import datetime
import logging
import os

from docopt import docopt
from wifitracker import sniffer, __version__


log = logging.getLogger(__name__)

if __name__ == "__main__":
    # parse commandline options:
    args = docopt(__doc__.format(basename=__file__), version=__version__)
    if args['--debug']:
        logging.getLogger().setLevel(logging.DEBUG)
    log.debug(args)
    log.info("PID: {}".format(os.getpid()))

    # execute command:
    if args['sniff']:
        try:
            start_dts = datetime.datetime.now()
            sniffer.sniff(args['<interface>'])
        except Exception as e:
            print e
